sudo: required

language: c

compiler:
- gcc
- clang

services:
- docker

arch:
  repos:
  - archlinuxfr=http://repo.archlinux.fr/$arch
  packages:
  - procps-ng
  - reflector
  - screenfetch-git
  mount:
  - ~/.pkg-cache:/var/cache/pacman/pkg
  - ~/.ccache:~/.ccache
# test space character in path
  - $HOME/y ay:$HOME/y ay
  before_install:
  - sudo sed -i '/#MAKEFLAGS=/c MAKEFLAGS="-j2"' /etc/makepkg.conf
  script:
  - sudo screenfetch
  - reflector --verbose -l 20 --sort rate -p https
  - echo $CC
  - touch test_file
  - |
    for ((i=0;i<10;i++)) ; do
      echo test$i
    done

script:
# build new image
- docker build --rm=true -t catergos/arch-travis:iso .
# run arch-travis to test new image
- bash ./arch-travis.sh
- ls -l

jobs:
  include:
  # push image to dockerhub
  - stage: build-push
    if: branch = master AND type != pull_request
    script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build --rm=true -t catergos/arch-travis:iso .
    - docker push catergos/arch-travis:iso
